---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: golang
    tag: "1.22-alpine"

inputs:
  - name: repo

params:
  DEPLOY_URL: ""
  DEPLOY_TOKEN: ""
  APP_VERSION: "latest"

run:
  path: sh
  args:
    - -exc
    - |
      cd repo
      go run ./cmd/deploy/main.go
